[package]
name = "bevy_examples"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
rand = "0.8.5"
rand_chacha = "0.3.1"
tokio = { version = "1", features = ["full"] }


[profile.dev.package."*"]
opt-level = 3
